spring.application.name=FlashSaleSystem

#Databse related Properties
spring.datasource.url = jdbc:mysql://localhost:3306/flashcart-app
spring.datasource.username=root
spring.datasource.password=Om_Pawar_214
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Redis configuration
spring.redis.host=localhost
spring.redis.port=6379

#kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=flashcart-group
spring.kafka.consumer.auto-offset-reset=earliest